### PR TITLE
Add option to not write build.txt

### PR DESCRIPTION
**Pull request by Rob--W**

### CODE REVIEW

**Comment by d-dolzhenko** [comment]
:+1:

**Comment by sammarland** [comment]
:+1:

**Comment by mateuszf** [comment]
:+1:

**Comment by crohrer** [comment]
:+1:

**Comment by eugef** [comment]
+1

**Comment by jrburke** [comment]
I went with a config value that was not a negative, `writeBuildTxt`. Will be part of the 2.2 release (still need to move the bugs over to the new milestone).

**Pull request closed without merging**
