### PR TITLE
Fixes #915 - changes the regular expression and removeStrict function…

### LINKED ISSUE #915: Pragma does not remove "use strict" from file contents
Setting the **useStrict****:** **false** option does not remove **"use strict"** from file contents, as described here: [Set the useStrict option in the build options](https://github.com/nesk/network.js/commit/64c6c06b11fce78158bab1b8d1d1b0f42bba0a80)

This option is not doing anything. Version 2.2.0

### PR DESCRIPTION
**Pull request by fab1o**
… to remove "use strict"

have a CLA on file.

### CODE REVIEW

**Comment by fab1o** [comment]
I used a different email for he CLA, just signed it again now

**Comment by fab1o** [comment]
@jrburke @millermedeiros Please could you merge this so we can have the useStrict fixed on master branch?

**Comment by jrburke** [comment]
Sorry for not posting back sooner. I will close this temporarily and comment in #915 shortly, as this undoes a change that was purposely done. Once we sort out the details in #915 we can reopen later if needed.

**Comment by fab1o** [comment]
Thanks!

**Pull request closed without merging**
